/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisuelsRouteImport } from './routes/visuels'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetsSlugRouteImport } from './routes/projets.$slug'

const VisuelsRoute = VisuelsRouteImport.update({
  id: '/visuels',
  path: '/visuels',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsSlugRoute = ProjetsSlugRouteImport.update({
  id: '/projets/$slug',
  path: '/projets/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/visuels': typeof VisuelsRoute
  '/projets/$slug': typeof ProjetsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/visuels': typeof VisuelsRoute
  '/projets/$slug': typeof ProjetsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/visuels': typeof VisuelsRoute
  '/projets/$slug': typeof ProjetsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/visuels' | '/projets/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/visuels' | '/projets/$slug'
  id: '__root__' | '/' | '/visuels' | '/projets/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VisuelsRoute: typeof VisuelsRoute
  ProjetsSlugRoute: typeof ProjetsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visuels': {
      id: '/visuels'
      path: '/visuels'
      fullPath: '/visuels'
      preLoaderRoute: typeof VisuelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets/$slug': {
      id: '/projets/$slug'
      path: '/projets/$slug'
      fullPath: '/projets/$slug'
      preLoaderRoute: typeof ProjetsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VisuelsRoute: VisuelsRoute,
  ProjetsSlugRoute: ProjetsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
